const ActionTypes = {
  FETCH_POKE_LOADING: 'FETCH_POKE_LOADING',
  FETCH_POKE_SUCCESS: 'FETCH_POKE_SUCCESS',
  FETCH_POKE_FAILURE: 'FETCH_POKE_FAILURE',
  FETCH_POKE_INFO_LOADING: 'FETCH_POKE_INFO_LOADING',
  FETCH_POKE_INFO_SUCCESS: 'FETCH_POKE_INFO_SUCCESS',
  FETCH_POKE_INFO_FAILURE: 'FETCH_POKE_INFO_FAILURE',
};

export default ActionTypes;
